episode_guide: https://docs.google.com/spreadsheets/d/1HQRMJgu_zArp-sLnvFMDzOyjdsht87eFLECxMK858lA/

description_sources:
  - https://docs.google.com/spreadsheets/d/1M0Aa2p5x7NioaH9-u8FyHq6rH3t5s6Sccs8GoC6pHAM/

check_ep_descriptions_every_hours: 6
check_ep_guide_every_hours: 6
check_rss_every_hours: 1
oldest_rss_release_hours: 12

paths:
  arcs: ../arcs
  episodes: ../episodes
  metadata: ../metadata
  other_edits: ../other_edits

tvshow:
  en:
    title: One Piece
    sorttitle: One Piece
    originaltitle: One Pace
    genre:
      - Action
      - Adventure
      - Anime
      - Fantasy
      - Science Fiction
      - Comedy
      - Modern Odyssey
      - Sh≈çnen Jump
    premiered: 2013-03-27
    releasedate: 2013-03-27
    season: -1
    episode: -1
    status: Continuing
    year: 1999
    plot: 'As a child, Monkey D. Luffy dreamed of becoming King of the Pirates. But his
      life changed when he accidentally gained the power to stretch like rubber... at
      the cost of never being able to swim again! Years later, Luffy sets off in search
      of the "One Piece", said to be the greatest treasure in the world...


      ~


      One Pace is a fan project that recuts the *One Piece* anime in an endeavor
      to bring it more in line with the pacing of the original manga by Eiichiro Oda.
      The team accomplishes this by removing filler scenes not present in the source material,
      fixing animation errors and correcting subtitles.'
    lockdata: false
    customrating: TV-14
