part: 13
saga: Arabasta
title: Drum Island
originaltitle: ''
shortcode: DR
mkvcode: drumisland
description: When Nami falls ill, the crew makes a detour from Arabasta to seek medical
  help. They happen upon a winter island inhabited by a distrusting populace and a
  single doctor with a mysterious reindeer companion.

episodes:
- episode: '01'
  standard: FD2B4F32
  extended: ''
- episode: '02'
  standard: 8FDCC832
  extended: ''
- episode: '03'
  standard: 2971EF62
  extended: ''
- episode: '04'
  standard: 902076E8
  extended: ''
- episode: '05'
  standard: E7044DBE
  extended: ''
- episode: '06'
  standard: A5145C90
  extended: ''
- episode: '07'
  standard: B1D913B9
  extended: ''
- episode: 08
  standard: 9794072D
  extended: ''

info:
  status: ''
  manga_chapters: 129 - 154
  num_of_chapters: 26
  anime_episodes: 78 - 91
  episodes_adapted: 14
  filler_episodes: ''
  num_of_pace_eps: 8
  piece_minutes: 294
  pace_minutes: 231
  audio_languages: Jpn,Eng
  sub_languages: Eng,Es,Fr
  pixeldrain_only: ''
  resolution: 1080p
  arc_watch_guide: Pace
