part: 7
saga: East Blue
title: The Adventures of Buggy's Crew
originaltitle: ''
shortcode: TH
mkvcode: buggy
description: Buggy, after being defeated by Luffy, Zoro, and Nami, begins his quest
  to regain his body parts and his crew, and then he will get his flashy revenge on
  Luffy.

episodes:
- episode: '01'
  standard: E75794DB
  extended: ''

info:
  status: ''
  manga_chapters: 35 - 75
  num_of_chapters: 0
  anime_episodes: 46 - 47
  episodes_adapted: 2
  filler_episodes: ''
  num_of_pace_eps: 1
  piece_minutes: 42
  pace_minutes: 20
  audio_languages: Jpn,Eng
  sub_languages: Eng,Es, Fr
  pixeldrain_only: De
  resolution: 1080p
  arc_watch_guide: Pace
