name: One Pace Metadata Job (v2)

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: '>=3.13'
          #freethreaded: true

      - name: Install uv
        uses: astral-sh/setup-uv@main
        with:
          enable-cache: true

      - name: Run metadata updater
        env:
          GCLOUD_API_KEY: ${{ secrets.GCLOUD_API_KEY }}
          ONE_PACE_RSS_FEED: ${{ secrets.ONE_PACE_RSS_FEED }}
        run: |
          pushd ./src
          output_update="$(uv run main.py update 2> >(cat >&2))"
          popd

          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add arcs episodes
          git diff --cached --quiet || (git fetch --unshallow origin && \
            export METADATA_VERSION="$(git rev-list --count origin/v2)" && \
            pushd ./src && uv run main.py json && popd && \
            git add metadata && \
            git commit -m "${output_update} [automated]" \
          )
          git push
